version: '3.8'

services:
  # Container for building and compiling the simulator
  build_simulator:
    image: build_simulator:latest
    build:
      context: .
      dockerfile: dockerSetup/Dockerfile.builds  # Build image from Dockerfile
    volumes:
      - conf_volume:/app/conf  # Use the volume for conf
      - data_volume:/app/data  # Use the volume for data
      - reports_volume:/app/reports  # Use the volume for reports
      - ./src:/app/src:ro  # Mount source code in read-only mode
    networks:
      bridge:
        ipv4_address: "172.28.0.3"  # Static IP for build_simulator
    container_name: build_simulator

  # Container for running the simulator (isolated from each other)
  run_simulator:
    image: one_sim_run:latest  # Image for the run_simulator container
    build:
      context: .
      dockerfile: dockerSetup/Dockerfile.run  # Build image from Dockerfile
    volumes:
      - conf_volume:/app/conf  # Use the volume for conf
      - data_volume:/app/data  # Use the volume for data
      - reports_volume:/app/reports  # Use the volume for reports
    networks:
      bridge:
        ipv4_address: "172.28.0.4"  # Static IP for run_simulator
    container_name: run_simulator

  # Container for storing simulation reports (using busybox image)
  reports:
    image: one_sim_reports:latest  # Image for the reports storage container
    build:
      context: .
      dockerfile: dockerSetup/Dockerfile.reports  # Build image from Dockerfile
    networks:
      bridge:
        ipv4_address: "172.28.0.5"  # Static IP for reports_storage
    container_name: reports_storage
    volumes:
      - reports_volume:/app/reports  # Use the volume for reports

networks:
  bridge:
    driver: bridge
    ipam:
      config:
        - subnet: "172.28.0.0/16"  # Define the subnet for the bridge network

volumes:
  conf_volume:
    driver: local
  data_volume:
    driver: local
  reports_volume:
    driver: local
