# Use busybox image for lightweight container
FROM busybox:latest

# Set up working directory
WORKDIR /app/reports

# Copy reports from host to container
COPY ./reports /app/reports

# This container has no process to run. It just stores the reports.
CMD ["tail", "-f", "/dev/null"]
