# Start with an openjdk image for building the simulator
FROM openjdk:8-jdk-slim as build_simulator

# Set the working directory
WORKDIR /app

# Copy your source code
COPY . /app

# Build the application
RUN chmod +x /app/scripts/compile.sh && ./scripts/compile.sh

# Final image should have compiled output
